### ISSUE TITLE
Fuse is difficult to remove, needs to be moved on Esp32

### ISSUE THREAD

**Issue by madhephaestus** [acamilo/RobotInterfaceBoard#13]
The fuse on the Esp32 is very difficult to remove. If it were moved close to the HV rial, then it would be much easier. Pliers need a 15mm keep-away on either side of the open section of the fuse holder. Right now both the switch and the delicate antenna are in the way fr a clean fuse removal.

**Comment by acamilo** [comment]
Replaced both fuses with a blade style automotive fuse.
