### ISSUE TITLE
4k7 ohm pullups to 3.3v are needed on SDA and SCL

### ISSUE THREAD

**Issue by madhephaestus** [acamilo/RobotInterfaceBoard#19]
A pullup between SDA and 3.3 and SCL and 3.3 is needed for stable I2C communications across all commercially availible Wii devices. SOme devices have pullups built in, but these devices are unaffected by the external pullups. Some devices do not have these resistors built in and are unstable on the board without them.

**Comment by madhephaestus** [comment]
This has been tested and validated as the stable solution in all cases for the Wii devices as a single device on the i2C port. When busing, this may be an issue.

**Comment by madhephaestus** [comment]
Note this is needed on both the ESP32 and the Teensy

**Comment by acamilo** [comment]
commit ecb4b3a3e98c0dec2cd3e581c8bc03964b119612
