### ISSUE TITLE
Fuse for the 3.3v regulator is needed (Value is in question)

### ISSUE THREAD

**Issue by madhephaestus** [acamilo/RobotInterfaceBoard#21]
A fuse to gracefully fail after the 3.3v rail is plugged directly into gnd, or if the modules 3.3v rail is shorted directly to ground. I assume 75% of the regulators maximum output is sufficient. Be sure to also look at the power spec for the ESP development boards built in. This regulator has fried on a large-ish number of our testing boards. Changing those fusing is much better than replacing all of the power regulators *when* the students short power to ground.

**Comment by madhephaestus** [comment]
An additional LED for the 3.3v rail should be here added. I will need to be able to power the module on and see at a glance if all the power rails are up and running.

**Comment by acamilo** [comment]
commit 5c16eed2d937238d69e448bf987ce9fe361f2ba1
