### ISSUE TITLE
New SS lables for Analog and servo

### ISSUE THREAD

**Issue by madhephaestus** [acamilo/RobotInterfaceBoard#24]
the block of pins that can be analog are:
The ADC driver API currently only supports ADC1 (9 channels, attached to GPIOs 32-39).

They should have some sort of block label. The only area of the board visable to the user is between the 3 pin header and the 1xX header, so maybe highlight the IO or make it inverted colors?

PWM capable pins should be labled too as servos

**Comment by acamilo** [comment]
commit f520d1e9d8a9c18e37b3da901794a7398df4641f
