### ISSUE TITLE
Disconnect specific IO used by System Resources on ESP32

### ISSUE THREAD

**Issue by madhephaestus** [acamilo/RobotInterfaceBoard#26]
These should be availible in the 1xN header, but stop short of the 3 pin header bank. Thier SS should be changed from the GPIO lable to the name of the perpheral that is consuming them. 

Setting any flash GPIO to Servo the module fails to boot. Using the boot pin causes unreliable programming. Using the Wii pins causes the Wii to fail.

Used by Flash:
GPIO6
GPIO7
GPIO8
GPIO9
GPIO10
GPIO11

Used as boot flag:

GPIO0

Used by Wii

GPIO21
GPIO22
GPIO27 (Use this for controller detect)

**Comment by acamilo** [comment]
commit dbb14b5b5240ae22241172272293afaca3e0c966
