### ISSUE TITLE
Label servo possible pins with a "~"

### ISSUE THREAD

**Issue by madhephaestus** [acamilo/RobotInterfaceBoard#31]
On these pins:
2,4,12-19,21-23,25-27,32-33

place a ~ to denote servo capable. The library for servos on the ESP32 enforces this and will not start servo on any of the other pins.

**Comment by madhephaestus** [comment]
See this section in the (now official) esp32 servo library:
https://github.com/madhephaestus/ESP32Servo/blob/master/src/ESP32Servo.cpp#L119

**Comment by acamilo** [comment]
commit bc8adbd48c6331260e6b21ed062c8a8094448461
