### ISSUE TITLE
change to 5v power rail for sensors on 35,34,39,36, lables for 3.3v and 5v towards the outside

### ISSUE THREAD

**Issue by madhephaestus** [acamilo/RobotInterfaceBoard#37]
On these pins the power rail should be 5v. Some sensors, specifically AS5162, operate at 3.3v but require a 5v input supply for the internal regulator. 

A label indicating this should be placed to the outside of the of the IO bank. When looking at the board in the orientation where you can read the IO labels, the label of the 3.3 or 5v should be to the Left of the IO bank.

**Comment by acamilo** [comment]
commit cebc24349fbfd1455a2ff0a1fc8821febe6283d8
