### ISSUE TITLE
Version 5 fuse will hit the antenna

### ISSUE THREAD

**Issue by madhephaestus** [acamilo/RobotInterfaceBoard#40]
The esp32 antenna sticks out 6.5mm from the edge of the pins. 
The antenna keep-away is wrong.
More importantly, the fuse will collide with the esp32. 
The fuse should be moved to the right side and aligned so that its footprint is outside of (entirely to the right) the keepaway zone for the antenna.

**Comment by acamilo** [comment]
commit 20b6ec96d9e185f649e87e3419c40954de28a7cf
