### ISSUE TITLE
release format and repo contents

### ISSUE THREAD

**Issue by madhephaestus** [acamilo/RobotInterfaceBoard#42]
Never version control zip files nor "binaries" such as the gerbers. Every future checkout needs to clone that down now...

Gerber zip files and BOM belong in the release attached as binaries. A collaborator or potential user might want to produce a board, all they should need to look at is the release. 

I'm not trying to be nit-picky, its just that i want to be able to point students at this repo as an example of how to organize PCB's into version control.

**Comment by acamilo** [comment]
its in the history. no fixing that. I just RM'd them so they don't show up in the files.
