### ISSUE TITLE
It's possible to buy PCB in Italy

### ISSUE THREAD

**Issue by tombo9999** [acamilo/RobotInterfaceBoard#49]
Hi Alex :)
I'm Luca (from Italy). Yesterday I asked some questions to @madhephaestus
He helped me with ESP32encoder library (I'm just an hobbyist).

Sorry to bother you, but it's possible to buy the board? Thanks in advance.

Ciao, Luca

**Comment by madhephaestus** [comment]
At the moment this board is open source but not availible for sale. We designed it and manufacture them for WPI's Robotics Engineering undergraduate program. To manufacture it yourself you can take the zip file from master to OSHPark.

**Comment by tombo9999** [comment]
Thank you :)
