### ISSUE TITLE
Controller detect pin should go to the microcontroller

### ISSUE THREAD

**Issue by madhephaestus** [acamilo/RobotInterfaceBoard#9]
Both the ESP32 and Teensy should have the controller detect pin rout to an IO pin. If the controller detect needs a pull up or pull down to work, add that as well to the pin.

**Comment by acamilo** [comment]
49d743ca390d077daf4d072be6042b93ec0343ef

**Comment by madhephaestus** [comment]
which IO pin does it go to?

**Comment by acamilo** [comment]
32 on teensy and 23 on esp

**Comment by madhephaestus** [comment]
please move the controller detect to a non servo/non SPI pin. Pin GPIO27 is ideal. Did you add a pull-up or pull down?
